// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateProject struct {
	Name        string  `json:"name"`
	Version     string  `json:"version"`
	Description *string `json:"description"`
}

type UpdateProject struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Version     string  `json:"version"`
	Description *string `json:"description"`
}
